services:
  postgres:
    image: postgres:14.10-alpine
    container_name: demo-postgres
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo -d demo_db"]
      interval: 3s
      timeout: 2s
      retries: 20