spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db
    username: demo
    password: demo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:migration

server:
  port: 8080